export const ORDER  = {
  SET_TOTAL: "SET_TOTAL",
  UPDATE_TOTAL: "UPDATE_TOTAL",
  CHECKOUT: "CHECKOUT",
  ADD_SELECTED: "ADD_SELECTED",
  REMOVE_SELECTED: "REMOVE_SELECTED",
  CLEAR_TOGGLE: "CLEAR_TOGGLE"
};

export const ROUTES = {
  CHECKOUT_ORDERS: "/mock/orderService"
};