export const CONFIG = {
    SET_INIT_CONFIG: "SET_INIT_CONFIG",
    SET_CONFIG_VALUES: "SET_CONFIG_VALUES",
    SET_SAVE_CONFIG: "SET_SAVE_CONFIG",
    SET_INPUT_STATUS: "SET_INPUT_STATUS",
    SET_EXECUTING_SAVE_STATUS: "SET_EXECUTING_SAVE_STATUS",
    SET_LOADING_FORM_STATUS: "SET_LOADING_FORM_STATUS",
    SET_RESET_CONFIG: "SET_RESET_CONFIG",
};

export const MODAL = {
    TOGGLE_MODAL: "TOGGLE_MODAL",
};

export const CLASSIFIER = {
    CLEAR_FILE: "CLEAR_FILE",
    SET_FILE: "SET_FILE",
    SET_CLASSIFICATION: "SET_CLASSIFICATION",
    CLEAR_CLASSIFICATION: "CLEAR_CLASSIFICATION",
    SET_OPTION: "SET_OPTION",
    SET_EXECUTING_SAVE: "SET_EXECUTING_SAVE",
};

export const MESSAGE = {
    SET_MESSAGE: "SET_MESSAGE",
    SET_VISIBLE: "SET_VISIBLE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",
};

export const STATS = {
    SET_LAST_RES_DATE: "SET_LAST_RES_DATE",
    SET_LAST_RES_TIME_TAKEN: "SET_LAST_RES_TIME_TAKEN",
    SET_NUM_RES: "SET_NUM_RES",
    SET_RES_HIS: "SET_RES_HIS",
    SET_MODAL_DOWNLOAD_TIME: "SET_MODAL_DOWNLOAD_TIME"
};

export const NAV = {
    SET_ROUTE: "SET_ROUTE",
};
