export const QUERY = {
  UPDATE_QUERY: "UPDATE_QUERY",
  UPDATE_TABLE: "QUERY_UPDATE_TABLE",
  SUBMISSION_STATUS: "QUERY_SUBMISSION_STATUS",
  CLEAR_TABLE: "QUERY_CLEAR_TABLE",
};

export const ROUTES = {
  SUBMIT_QUERY: "/mock/query"
};
