export const CART = {
  ADD: "CART_ADD",
  REMOVE: "CART_REMOVE",
  CLEAR: "CART_CLEAR",
};

export const PRODUCTS = {
  SET_LOADING_PRODUCTS: "PRODUCTS_SET_LOADING_PRODUCTS",
  SET_PRODUCTS: "PRODUCTS_SET_PRODUCTS",
  SELECT_PRODUCT: "PRODUCTS_SELECTED_PRODUCT",
  UPDATE_QUANT: "PRODUCTS_UPDATE_QUANT"
};

export const ROUTES = {
  images : "/images/",
  products: "/mock/orderService"
};
